### ISSUE TITLE
solidity and go-ethereum/epm compatibility

### ISSUE THREAD

**Issue by androlo** [eris-ltd/epm-go#100]
Starting with web3 using our go-ethereum fork directly, working my way into using epm.

- [x] starting up `eris-ltd/go-ethereum` on `develop` with a rpc server running
- [x] accessing the client through `web3`
- [ ] deploying and working with contracts through `web3`.

Getting a bunch of errors when trying to do fairly basic stuff with `web3` right now, such as getting block numbers and compiling solidity contracts. This happens with both the `cpp-ethereum` and `go-ethereum` headless clients. I might just be screwing up all over sudden, but i suspect it is on their end, and a consequence of them not being able to access the cpp client as normal, while doing what seems to be some major refactoring. This was posted by Marek (one of their devs): https://github.com/ethereum/cpp-ethereum/issues/1260. I'm having issues as well.

This in turn seems to be caused by a number of minor faults following the poc8-poc9 transition. It should settle down. Meanwhile I am thinking about the solidity compiler, and checking if go-eth supports compiling solidity code. If not, then I guess we need to use our lllc compiler. Either way I'll get it running.

**Comment by ebuchman** [comment]
ya our sol compiler should be stable through lllc-server. don't think go-eth will compile it for you. but this is what the epm/lllc pipeline is for, so we can avoid eth instability as they change pocs.

**Comment by ebuchman** [comment]
but you're having these issues talking to our go-eth fork too?

**Comment by androlo** [comment]
I think the problems is with the rpc - javascript. not compiler related.

**Comment by ebuchman** [comment]
ah ok

**Comment by androlo** [comment]
or epm related for that matter

**Comment by ebuchman** [comment]
@androlo do you mind if I close this or you want it open for something?
