### ISSUE TITLE
EPM fetch should fetch the whole chain not just the genesis block

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#107]

**Comment by ebuchman** [comment]
fetch now ends by calling run. it needs to be killed manually. is this a problem?

**Comment by compleatang** [comment]
not a problem. having it go from fetch to run is fine. we can add a sleep plop the pid and kill it simply as part of the startup sequence for containers and folks can ctrl+c when their chains catch up when using from cli proper.

**Comment by compleatang** [comment]
@ebuchman if you agree with me on #113 then we'll close this as rejected.

**Comment by ebuchman** [comment]
Agreed
