### ISSUE TITLE
epm should wait for broadcast to peers post commit

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#108]

**Comment by ebuchman** [comment]
@compleatang I believe I have addressed this with a trivial change in https://github.com/eris-ltd/epm-go/commit/691ce2ca9e6fec2727723f64cadd96ec58d874f2#diff-1db9c3d77149ed0a6f0276e31706fd70L235

do you have a test for it? it was working locally on my machine even before this change

**Comment by ebuchman** [comment]
sorry easier to see here: https://github.com/eris-ltd/thelonious/commit/baaa9938ad9f6efad4da844d19b2206a572f5b69

**Comment by compleatang** [comment]
its a bit hard to recreate and it wasn't happening to me on develop. let's close for now and we'll reopen if it reappears.
