### ISSUE TITLE
prepare changelog, readme updates, site updates, and announcement of 0.9 release

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#115]
- [x] changelog
- [x] update version in epm help output
- [x] update thel versions in default configs
- [x] prepare updates to epm.io
- [x] prepare updates to thel.io
- [x] betterly do actual builds for folks (will need to use goXC with circle and GH probably)
- [x] prepare blog post for `eng` overviewing changes.

**Comment by ebuchman** [comment]
Changelog:
- rewritten lexer/parser
- support for arithmetic in s-expressions
- package imports and name spacing for nested deploys
-  expose public api to chain commands
- `TODO`: http bridge to public api
- full support for solidity/serpent and the ethereum ABI
- more thorough testing and CI support
- improved useability of commands (eg. plop, keys) and additional features (accounts/storage dump)
- general bug fixes
- tendermint module
