### ISSUE TITLE
exit and ifExit must be caught to provide a sane non cli service 

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#121]
there's a couple ways we can do this depending on how the http service wants to handle errors. @compleatang to be discussed

**Comment by compleatang** [comment]
agree. was thinking about this today. docker makes this a bit "harsh" as peers don't exit as gracefully as they should i think because we're not properly catching sigterms **or** because docker doesn't send sigterm (which would be a bigger issue). I need to investigate this a bit further tho.

**Comment by ebuchman** [comment]
hm not sure I see where docker comes in, as I believe this is mostly a go thing. Really it's about the fact that none of the functions in `epm/commands` return anything, and either print to screen or exit. so we need to rather package and return a response with an error that the caller can use.

**Comment by compleatang** [comment]
handled via `eris`.
