### ISSUE TITLE
multiple binaries for different chains and clever switching 

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#129]
It would also be nice to vendor the modules, as the extra indirection is a pain with go dep. 

On the other hand, maybe we remove all the blockchain deps from epm repo, and count on modules instead, so epm itself can be more light-weight and easier to dev-in new blockchains without godep annoyances.

**Comment by ebuchman** [comment]
Step by step proposal
- [ ] the base epm install lacks any blockchain modules
- [ ] makefile and a script for generating one binary per chain (will involve parsing some of the epm code AST)
- [ ] commands like new, run, deploy, cmd, fetch, etc. check the chain type and then rerun the command using the appropriate binaries. the base epm will have a different compile path for these commands than the chain specific binaries
- [ ] if the necessary binary doesn't exist, run the script to generate it so we can still install just from `go get` without having to run `make`

**Comment by ebuchman** [comment]
as much as I want to be working on this (not having it slows down dev with the nonsense of godeps and the secp256k1 import issue), there will be major merge issues against the epm serve work, so it probably should wait

**Comment by compleatang** [comment]
strategy wise :+1:

**Comment by ebuchman** [comment]
this is done and sexy
