### ISSUE TITLE
Up default gas in modules/eth

### ISSUE THREAD

**Issue by androlo** [eris-ltd/epm-go#133]
Not an epm issue per se but since it's in godeps dir. upped https://github.com/eris-ltd/epm-go/blob/develop/Godeps/_workspace/src/github.com/eris-ltd/modules/eth/eth.go#L34 to 100k instead of 10k. Worked. Seems gendoug costs about 20k to deploy.Please if you could increase that value, not sure to what but at least 100k or so.

**Comment by androlo** [comment]
solidity version of gendoug that is

**Comment by compleatang** [comment]
i'll handle this tomorrow. i have to update modules to add rpc to the interface anyway.

**Comment by compleatang** [comment]
Looks like @ebuchman already handled: https://github.com/eris-ltd/modules/commit/eec40f80b046105449e6d205f049eb18629ea4e2
