### ISSUE TITLE
epm accounts does not display proper account info

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#134]
I have only witnessed this on eth chains i haven't tried thel it might work there. When i do 

epm accounts myaddresshere

it returns

Balance: 5c3e70
Nonce: 0

It will also do this if i sub in any other address or even "addresses" which don't exist... do you know why?

**Comment by ebuchman** [comment]
It gives this invalid balance?

**Comment by dennismckinnon** [comment]
yes every account i inspect gives that balance even the ones that don't exist.

**Comment by compleatang** [comment]
is this fixed? i cannot reproduce.
