### ISSUE TITLE
fix refs command to allow epm refs --help

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#135]

**Comment by compleatang** [comment]
this is a bug with the cli lib. can't find the issue just now (but its related to https://github.com/codegangsta/cli/pull/202#issuecomment-89494387). 

At any rate `epm refs help` works while

`epm refs --help` 

and

`epm refs -h` 

do not.

**Comment by compleatang** [comment]
also related: https://github.com/codegangsta/cli/pull/172

**Comment by ebuchman** [comment]
hm interesting. should we just let it go then? maybe make a note somewhere? seems like itll be fixed soon enough

**Comment by compleatang** [comment]
my vote is to leave as open issue so we remember to keep an eye on when fixed in lib, but we can keep as a milestone free issue for now.

**Comment by compleatang** [comment]
handled elsewhere.
