### ISSUE TITLE
should epm testing spin up a lllc-server docker container?

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#138]
right now epm testing depends on our public server. should we instead have it spin up its own server so it doesn't have that external dependency? on the other hand, since the lllc-server is critical to anyone who might just download and run epm-go, maybe it  should fail if the server is down ...

**Comment by compleatang** [comment]
y u no close automatically?

we can use new relic to alert us when lllc is down. better to have stability in the testing I think.

**Comment by ebuchman** [comment]
it only closes automatically on merge to master
