### ISSUE TITLE
Convenience vars available within pdx 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#147]
- [ ] myaddr 
- [ ] chainid 
- [ ] env vars expansion

Accessed as normal vars syntax but parsed post deploy vars.

**Comment by ebuchman** [comment]
so lets say:
- [ ] {{ADDR}}
- [ ] {{CHAINID}}
- [ ] {{ENV:VARNAME}}

**Comment by dennismckinnon** [comment]
sounds good i assume these values are read-only somehow?

**Comment by ebuchman** [comment]
meh i figure its like python. overwrite at your own risk...

**Comment by compleatang** [comment]
:+1: 

Don't think its epm's responsibility to manage overwrites at this point. If there's demand for overwrite protection we can add to a later version.
