### ISSUE TITLE
State examination does not behave as expected

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#152]
This isn't really a bug Its just behaviour that I wasn't expecting.

I was using the following .pdx

```
  1 deploy:
  2     gendoug.sol => {{gendoug}}
  3 
  4 transact:
  5     {{gendoug}} => addPerm "bobbyjoe"
  6 
  7 # commit:
  8 call:
  9     {{gendoug}} => permExist "bobbyjoe" => {{exist}}
 10 assert:
 11    {{exist}} => 0
```

The assert fails because the call returns 1 meaning the permission was created. But the commit is commented out. So based on my conversations with you @ebuchman this shouldn't fail.

I am guessing that we are using the temp post state as if the transaction had been mined meaning the commits i have been putting in everywhere are largely unnecessary.

This is a nice easy one to close since it just involves explaining why even without the commit the call sees the post state. Also should I still be using these excessive commits? why?

**Comment by ebuchman** [comment]
the call should not see the post state unless a block is mined. I wonder if there's something hidden that makes it mine a block before the call? that is weird...

**Comment by dennismckinnon** [comment]
Irc definitely not being mined WAY too quick

this is ethereum so its possible they make the post state accessible when reading storage? I can try to make a test for thelonious too.

**Comment by compleatang** [comment]
closing this issue for now. let's reopen if it persists on the 0.10 stack.
