### ISSUE TITLE
Remove all chain deps from epm-go and instead depend on eris-ltd/modules

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#155]
One thing I'd really appreciate during dev is easy switching between vendored and local deps. I've added a `got deps` command to help with rewriting imports but the fact that chains are vendored into modules which is then vendored into epm-go is awful. also the epm repo is so bulky that using git in it is actually slow. 

So I'd like to remove all the chain Godeps and instead reference `eris-ltd/modules`. This means the repo would not contain all its dependencies anymore, and would rely on `go get` to fetch the modules directory, which would be fully vendored.
Thoughts?

**Comment by compleatang** [comment]
:+1: 

The repo is huge and ideally we can move these conflicting crypto libs out of EPM itself which will make it installable on windows as well as more flexible. Obviously this would have to be integrated with multibinaries work.

**Comment by compleatang** [comment]
i think current discussions have deprecated this, no? lets close if you agree @ebuchman

**Comment by compleatang** [comment]
done. `eris chains` || `eris services` FTW.
