### ISSUE TITLE
Clean up help materials

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#156]
This is just a minor detail some subcommands have incomplete or unhelpful help information. I would be willing to go through and ensure its complete and up to date for all commands if you show me how to edit the help material.

**Comment by compleatang** [comment]
Help messages are here: https://github.com/eris-ltd/epm-go/blob/develop/cmd/epm/commands.go#L106

There is a known issue within the cli lib we use which is that `epm keys help` and `epm keys --help` do not work (but `epm keys -h` ) does work. (This applies to all the subcommands but just using `keys` as an example). 

@ebuchman and I are tracking that issue in the CLI lib and once it gets fixed will be easier to work with subcommands.

**Comment by compleatang** [comment]
handled via the move to `eris`
