### ISSUE TITLE
Generate and drop a raw genesis.json with config defaults into current directory

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#158]
Not sure what this command should be called, but it would be helpful to just plop a default genesis in current directory so that over time that genesis.json could be updated (as, say, public key addresses came in from developers) and a new chain hashed with `--genesis ./genesis.json` flag from same dir.

**Comment by ebuchman** [comment]
lol this use to be what plop did! `epm plopfile` ?

**Comment by compleatang** [comment]
i know! `epm plop default` ...?

**Comment by compleatang** [comment]
`eris chains new` :fire_engine:
