### ISSUE TITLE
epm keys daemon for unified and more secure key management

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#159]
A key daemon with a leveldb store and AES encrypted keys.
Private keys are encrypted with AES, where encryption key are derrived from password ala PBKDF2 .
Encrypted blobs are stored in leveldb under their public address (possibly chain dependent but should be fine). The leveldb store should be backed up outside the .decerver dir.

Requests are made to the daemon with address, chainType, blob, and password. A signature is returned or details with a related error.

Requests can also be made for a particular address' public key. 

EPM will manage a set of `refs` for keys. 
Refs will be stored as files at `~/.decerver/keys/refName-hexAddr`, 
and will be either empty or contain their public key (for caching). 
The keys dir should also have some sort of configuration file for setting the daemons port (maybe itll be on a unix socket).

The EPM blockchain interface will gain an additional Signer interface, which will manage
requests to the key daemon and will store the password in memory for repeated calls within a process,
though it should contain a timeout (say 5 minutes or so).

Essentially this means commands like Script(), Msg(), Transact() will use their underlying chain's libraries to compose transactions and binary encode, and will then pass them out through the Signer (which is not implemented independently in each module, but registered with them) to get a signature, and then broadcast to the chain.

After parsing epm commands, if one will require a signature, the terminal user will be prompted.
EpmServe should be able to take (https encrypted) passwords from users and pass them along to the Signer interface as necessary.

**Comment by ebuchman** [comment]
break down of how ssh pub keys are secured: https://martin.kleppmann.com/2013/05/24/improving-security-of-ssh-private-keys.html

**Comment by compleatang** [comment]
This is great. Very necessary.

`keys ls` is done. Although it may need massaging. I've also implemented `keys use` which already works off refs (but probably needs to be refactored a bit with some of the work abstracted so more widely usable).

vote for this daemon to be implemented as a microservice which we can use either as a long running process or a quick spin up as needed by developers. 

the long running process scenario would be to sign as the node itself (i suspect this would mainly be used by verifier nodes that were mostly there to commit blocks). quick spin up process scenarios will probably be when developers need grab a different key and sign before sending a tx either as temp keys or just another (authorized) key in the keychain. this design would help us toward the multiple key testing environment we will be needing for more complex smart contract systems testing. note, nothing in here seems to conflict with the above.

epm serve can then be configured to either allow transactions signed by the node's key or not and if not how to use the keystore (temp keys, exposed keys, as users require). this would just be a configuration setting on boot up so should be fairly straightforward.

**Comment by ebuchman** [comment]
lets talk through this a bit tomorrow. the basic cli version is just about done. I basically borrowed heavily from eth's crypto/key* but  changed a few things and adapted to allow tendermint keys too and hopefully more in the future. keys can be AES-GCM encrypted. I've been having trouble coming to terms with holding passwords in memory, and with how to conveniently/crossplatformly get the daemon going as another user with restricted permissions. so right now its just a cli that we will exec out to.

**Comment by compleatang** [comment]
done. see eris-keys.
