### ISSUE TITLE
`--docker` mode

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#161]
epm should have a `--docker` mode. this should be the default mode when installed.

when epm was placed in this mode it would interact with a blockchain which was running in a container rather than natively on the host machine. this will have significant upsides, particularly for windows developers. it will also make our epm tool be much more lightweight and easily built for all OS'es with GoXC.

the work necessary to add this feature will be focused mostly in two areas:

* setting environment variables
* mounting volumes

however the full set of work necessary to add this feature is below:

- [ ] graceful docker/docker-compose installed check
- [ ] add a `containers` folder to main eris folder (see #160 for my opinion)
- [ ] build a spec for what we need to store in a json file (volume mount mappings, env vars)
- [ ] add a global `epm` config into main eris folder
- [ ] determine what global configs we'd need for `--docker` mode
  - [ ] allow overwrites on a per blockchain/container basis ...?
- [ ] map commands through a docker socket call

**Comment by androlo** [comment]
I agree 100% with this. The nature of multi-chain issues has certainly changed after we switched over to node.js, and all our secondary stuff have proper js rpc libs (eth, bitcoin, ipfs, etc.), so the big issue as I see it is how to start rpc servers. If that can be made easier through docker, and we provide that solution, that would be fantastic. Then I think we're truly doing multi chain/tool management well.

**Comment by compleatang** [comment]
`eris` tool will handle this.
