### ISSUE TITLE
improvements, cleanup, clarification

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#164]
Instead of making a bunch of issues for this. This is going to be the one stop shop for throwing up improvements and fix ideas. Top comment will be ones we have agreed are good ideas. conversation over potentials in subsequent comments. All ideas will be categorized as 0.9, 0.10.0, 0.10.1, or future.

*0.9*

*0.10.0*

*0.10.1*

*future*

**Comment by dennismckinnon** [comment]
ideas:
[ ] - epm filename.pdx should run the .pdx file there isn't any reason I see that running pdx's should be a subcommand
[ ] - all the epm cmd * commands should just be epm *
[ ] - all epm * commands should be parsable in pdx
[ ] - introduce global vars available across chains.

discussion:
[ ] - we need to better handle editing of existing contract suites with the abi compatibility. This is likely not going to be easy.

**Comment by dennismckinnon** [comment]
bugs:
[ ] - set in pdx does not seem to work

**Comment by dennismckinnon** [comment]
epm-walkabout is now available containing some contracts and .pdx files. pretty good for testing if shit is working

**Comment by compleatang** [comment]
these are worthy of discussion but until we split out the tools this will be blocking. let us focus on that effort now and revisit these post tool split.

**Comment by dennismckinnon** [comment]
sure just Ideation and discussion issue

**Comment by dennismckinnon** [comment]
epm set seems to try to store data based on a guessed type from the first character. for example:

`epm set bob 1234baced` stores 1234 in bob and drops the rest.

This is kind of unintuitive though I think I understand why it happens since you have to judge what type to create as you go character by character.

I see two possible ways to resolve the confusion when not quoted or proceeded by 0x:

first: Start at the most restrictive character set (0-9) and perform current routine until unrecognized character is found then move up to next type which includes that character. (if is was a-f,A-F then move up to a hex interpretation other wise jump to string) continue until whitespace found.

second: require that 0x is always used in front of hex and quotes used around strings. if we did this then we would need to ensure uniform output across the board to avoid confusion.

I honestly am not sure which solution I prefer. While I think the second is clearer, the first one is probably nicer to use despite its hidden behaviours.
