### ISSUE TITLE
fix `epm plop chainid`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#165]
current output on develop is:

```
Chain type: thelonious
561b7fcffbc20d4b9ed921a32bf89915465edcb8
```

but all of our dapp start scripts rely upon that plop being:

```
561b7fcffbc20d4b9ed921a32bf89915465edcb8
```

only.

**Comment by dennismckinnon** [comment]
So @ebuchman can confirm but its currently printing out the chain type because of the binary generator. He told me that it was vital for debugging purposes. Maybe it would be better to hide it as a warning rather then comment it out completely?

**Comment by compleatang** [comment]
well he can merge that PR or not, but currently it fucks up all the plop commands.

**Comment by ebuchman** [comment]
ya sorry bout that. the binaries are pretty stable by now. merged.
