### ISSUE TITLE
users/workflows discussion

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#169]
users

1) dapp dev wants nothing but simple env for smart contracts and js in his browser
2) dapp dev wants more control over chains, wants to deploy own with custom settings, manage, maybe have many, learn to do atomic swaps and cross chain contracts, etc.
3) similar to 2, but sys admin/it for companies that use the tool for plumbing/managing the companies chain/s
4) us, and devs working on chains themselves
5) other services that use our apis to provide higher level interfaces, ui, etc

**Comment by androlo** [comment]
Seems right to me, although in (1) maybe include node.js as well as the browser (not really an issue  since tendermint-rpc-js supports both).

**Comment by compleatang** [comment]
:+1:

**Comment by agatkin** [comment]
For workflow, I'm looking for #1 and #2.  As a newbie dev I need a multichain swiss army knife like epm.  I don't want to use/learn/install cutting edge alethzero/bitcoind/tendermint + epm.  I'd rather have epm with older more stable builds of the other chains for my cross chain dapp testing and deployment.  I'd like to learn a single tool (epm) ideally.  Slowness/performance is really not something I worry about, it's the steep learning curve and instability of all the other chain specific tools.

For that reason I'd rather not have it cut up per #161 into a thel only tool.

**Comment by compleatang** [comment]
this issue is closed. `eris` will handle all this smoothly for users.
