### ISSUE TITLE
Fatal error gmp.h'

### ISSUE THREAD

**Issue by ChristopherA** [eris-ltd/epm-go#170]
$ go version
go version go1.4.2 darwin/amd64
$ go get github.com/eris-ltd/epm-go/cmd/epm
# github.com/eris-ltd/epm-go/Godeps/_workspace/src/github.com/obscuren/secp256k1-go
In file included from ../projects/go/src/github.com/eris-ltd/epm-go/Godeps/_workspace/src/github.com/obscuren/secp256k1-go/secp256.go:11:
In file included from ././secp256k1/src/secp256k1.c:5:
In file included from ././secp256k1/src/impl/num.h:8:
In file included from ././secp256k1/src/impl/../num.h:9:
././secp256k1/src/num_gmp.h:8:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^
1 error generated.
$

Using a Mac using latest OSX.

**Comment by dennismckinnon** [comment]
The error is pretty clear. you do not have gmp installed. For OSX you should be able to get it through

brew install gmp

Let me know if that helps.

**Comment by ChristopherA** [comment]
Thank you. Can you change this issue to:

a) document that you need to install gmp, and if you have brew to install it that way.
b) consider using brew instead of go get to install epm-go.

**Comment by dennismckinnon** [comment]
I'm glad it worked. 
for a) we do have it documented in our main tutorial But I'll make sure to add it to the other ones too. Can you tell me which tutorial you were using that it wasn't included for?
b) Thanks for the input, I'll put it on our next meeting agenda.

**Comment by ChristopherA** [comment]
I followed https://github.com/eris-ltd/epm-go#install

**Comment by dennismckinnon** [comment]
Thank you I have made the appropriate edit!

If you didn't know we have some more in depth tutorials available on our site. As well as a work in progress tutorial here https://github.com/eris-ltd/epm-walkabout which i find interesting but comes with the caveat that it uses the develop branch of epm which can be unstable. And hasn't been fully vetted.
