### ISSUE TITLE
eth only using rpc on develop branch

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#173]
trying to run any eth chain command on the latest develop results in:

```
dennis@Juzo:~/Documents/epm-walkabout$ epm deploy example1_1.pdx
2015/05/09 09:12:38 Eth rpc not implemented yet
```

which I have tracked to the ethereum modules.go

So does epm use rpc by default now? If so how can I tell it not to for ethereum since its rpc capabilities are not yet implemented?

**Comment by compleatang** [comment]
closing issue. handling this via eris contracts rework.
