### ISSUE TITLE
Error on chain install: Error building Tendermint Exit Status 2

### ISSUE THREAD

**Issue by rfikki** [eris-ltd/epm-go#176]
Cannot complete make without this error.

rfikki@rfikki-Virtual-Machine:~/go/src/github.com/eris-ltd$ cd epm-go
rfikki@rfikki-Virtual-Machine:~/go/src/github.com/eris-ltd/epm-go$ ls
chains      commands            epm      Makefile   start.sh
circle.yml  docker-compose.yml  Godeps   README.md  test.sh
cmd         Dockerfile          LICENSE  server     utils
rfikki@rfikki-Virtual-Machine:~/go/src/github.com/eris-ltd/epm-go$ which make
/usr/bin/make
rfikki@rfikki-Virtual-Machine:~/go/src/github.com/eris-ltd/epm-go$ make
go install ./cmd/epm-binary-generator
epm-binary-generator ./cmd/epm ./commands thelonious tendermint ethereum
# github.com/eris-ltd/epm-go/Godeps/_workspace/src/github.com/tendermint/tendermint/binary
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:171: constant 4294967296 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:174: constant 1099511627776 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:177: constant 281474976710656 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:180: constant 72057594037927936 overflows uint
Error on chain install: Error building tendermint exit status 2

**Comment by ebuchman** [comment]
Can you give us the output of `go version` please? Are you on a 32 bit machine?

**Comment by rfikki** [comment]
rfikki@rfikki-Virtual-Machine:~$ go version
go version go1.4.2 linux/386
rfikki@rfikki-Virtual-Machine:~$

**Comment by rfikki** [comment]
I was able to get past this error after playing with go env. I had to change the GOROOT setting to GOROOT="/usr/lib/go"

**Comment by ebuchman** [comment]
ah looks like you are on 32-bit machine. not sure how changing the GOROOT would fix it tho!

**Comment by rfikki** [comment]
Intel Core I7 (64 bit) 2.4GHz

**Comment by jaekwon** [comment]
Tendermint assumes a 64bit architecture w/ 64bit golang.  Is this a problem?

**Comment by rfikki** [comment]
Did not realize that. I had to install some 32 bit distro way back when installing go and minGW. I will update that since it seems those requirements have changed.

**Comment by ebuchman** [comment]
hm ok. so it was a 32-bit version of golang but you have a 64bit version too so you're ok? an issue's been opened on the appropriate repo to support 32-bit archs: https://github.com/tendermint/tendermint/issues/72.

closing this. if needed you can reopen.

**Comment by paulrd** [comment]
I'm getting the following on the Arm6 raspberry pi (32-bit):

```bash
go install ./cmd/epm-binary-generator
epm-binary-generator ./cmd/epm ./commands thelonious tendermint ethereum
# github.com/eris-ltd/epm-go/Godeps/_workspace/src/github.com/tendermint/tendermint/binary
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:171: constant 4294967296 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:174: constant 1099511627776 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:177: constant 281474976710656 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:180: constant 72057594037927936 overflows uint
Error on chain install: Error building tendermint exit status 2
```
