### ISSUE TITLE
[EPM-CLI] Ref * already exists when fetching chain but no actual refs 

### ISSUE THREAD

**Issue by zqa19** [eris-ltd/epm-go#180]
When fetching a chain, 
2015/05/28 02:01:12 [EPM-CLI] Ref * already exists
occurs in terminal, but no refs shown in 'epm refs' or in blockchains/refs.
Deleting the entire folder .eris and 'epm init' doesn't always work.

**Comment by compleatang** [comment]
Closing this for now as this pipeline is being revamped in the eris-cli repository for our 0.10 stack release.
