### ISSUE TITLE
EPM; Result error.(Solved!)

### ISSUE THREAD

**Issue by BeyondLimitation** [eris-ltd/epm-go#182]
![image](https://cloud.githubusercontent.com/assets/10960326/8545139/5c1b4bb4-24e6-11e5-92a3-79cd946719c2.png)

![image](https://pbs.twimg.com/media/CJDz9NcVAAA70es.png)

My OS: **Ubuntu Linux 14.10 64bit**
Go language version: **go version go1.4.2 linux/amd64**
Installed Development tools: **Eris industries products, Alethzero**

Detail: I cloned this one-->https://github.com/eris-ltd/epm-walkabout
and move these files to **~/.eris/dapps/epm-walkabout/contracts**.

And follow this tutorial->https://github.com/eris-ltd/epm-walkabout/blob/master/epm-walkabout.md#keys-todo

In this tutorial, i have to get this result below `0x00000000000000000000000000000000000000000000000000000000feedface `
But mine, as you can see the pictures above, i can't get any result or get a result with cut!

Umm.. I just clone them and follow tutorial..What's the reason? And how to solve it?

**Comment by compleatang** [comment]
is this resolved? pinging @dennismckinnon

**Comment by dennismckinnon** [comment]
It is not immediately clear what is going on here. as you can see below. I just ran the very same commands and got the correct result.

```
dennis@Juzo:~/Documents/epm-walkabout$ epm head
ethereum/default
dennis@Juzo:~/Documents/epm-walkabout$ epm cmd deploy example1.sol test
2015/07/10 08:34:17 [EPM] Executing job: deploy
2015/07/10 08:34:17 [EPM] Deployed 0x21e9e7374b129548809fff2f2fa60f05c80f9f50 as test
Storing: test 0x21e9e7374b129548809fff2f2fa60f05c80f9f50
dennis@Juzo:~/Documents/epm-walkabout$ epm cmd call {{test}} get output
2015/07/10 08:35:33 [EPM] Executing job: call
Storing: output 0x00000000000000000000000000000000000000000000000000000000feedface
2015/07/10 08:35:33 [EPM] Sent [get] to 0x21e9e7374b129548809fff2f2fa60f05c80f9f50
2015/07/10 08:35:33 [EPM] Result: 0x00000000000000000000000000000000000000000000000000000000feedface
```

can you confirm that you are running this on an "eth" chain?

**Comment by BeyondLimitation** [comment]
@dennismckinnon 
See? I have ether and checked **'ethchain'** But still have a problem.
![image](https://cloud.githubusercontent.com/assets/10960326/8634037/1e120774-2822-11e5-9eb2-1fb9ef70f3a6.png)

**Comment by BeyondLimitation** [comment]
@dennismckinnon Plus, 'example1.sol' data is not changed.

![image](https://cloud.githubusercontent.com/assets/10960326/8634039/5c2b37ba-2822-11e5-89bd-bf5fba2a6bec.png)

**Comment by BeyondLimitation** [comment]
@dennismckinnon Wait! I change that solidity file's data , i got correct result!

![image](https://cloud.githubusercontent.com/assets/10960326/8634396/0bf9f672-2832-11e5-9736-4a8a8222dfb7.png)

**Comment by dennismckinnon** [comment]
I see the problem. YOu must have edits the file because you have `value = 0xFEEDBACK` which is not valid hex. There was a compiler error. resulting in the EMPTY CODE! messages.

you should be able to change it back to `value = 0xFEEDFACE` and it should work also.

**Comment by BeyondLimitation** [comment]
@dennismckinnon Thanks. I finally know why this happen to me and solved this problem!
Appreciate your help.

**Comment by dennismckinnon** [comment]
Glad I could help
