### ISSUE TITLE
Issue  encountered with Make 

### ISSUE THREAD

**Issue by bartcant** [eris-ltd/epm-go#183]
After executing the "Make" command the system errors out with the following information

go install ./cmd/epm-binary-generator
epm-binary-generator ./cmd/epm ./commands thelonious tendermint ethereum
Error on chain install: Error building tendermint exit status 2

**Comment by ebuchman** [comment]
is this on a fresh install? have you changed any files? you can build only the chain you want with `make thelonious` or `make tendermint` or `make ethereum`

**Comment by bartcant** [comment]
Fresh Epm-go  install from this morning  on Ubuntu14.04 environment (in VMware)
Make thelonious works
Make ethereum works
same error message on tendermint chain

**Comment by bartcant** [comment]
![2015-07-09-111827_488x547_scrot](https://cloud.githubusercontent.com/assets/11460724/8602857/825d43ce-2629-11e5-9562-a342427b878a.png)

**Comment by ebuchman** [comment]
aha! Are you on a 32-bit machine or using a 32-bit version of go?

**Comment by bartcant** [comment]
good observation. I just checked and I installed 32 bit for go.  I'll reinstall 64bit version and re-test

**Comment by ebuchman** [comment]
Great. It's actually our most common gotcha! Tendermint will support 32-bit arch soon. Let us know if it works for you when you reinstall.

**Comment by bartcant** [comment]
Yes. works on 64 architecture

**Comment by ebuchman** [comment]
Great :)

**Comment by pralhdes** [comment]
Folks, I am facing this error. Its a 64 bit Ubuntu 14.04 vm and a 64 bit go installation. 

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ sudo -E make
go install ./cmd/epm-binary-generator
epm-binary-generator ./cmd/epm ./commands thelonious tendermint ethereum
make: epm-binary-generator: Command not found
make: *** [all] Error 127

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ go version
go version go1.4.2 linux/amd64

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ uname -a
Linux host-9-122-79-38 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

ubuntu 14.04


user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ sudo -E make binary
go install ./cmd/epm-binary-generator

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ sudo -E make tendermint
epm-binary-generator ./cmd/epm ./commands tendermint
make: epm-binary-generator: Command not found
make: *** [tendermint] Error 127

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ sudo -E make ethereum
epm-binary-generator ./cmd/epm ./commands ethereum
make: epm-binary-generator: Command not found
make: *** [ethereum] Error 127

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ sudo -E make thelonious
epm-binary-generator ./cmd/epm ./commands thelonious
make: epm-binary-generator: Command not found
make: *** [thelonious] Error 127

**Comment by ebuchman** [comment]
I suspect you have not put `$GOPATH/bin` on your `$PATH`

When you run `go install` it will install the resulting binary into `$GOPATH/bin`, so unless you put that on your path, the binary can't be found

**Comment by pralhdes** [comment]
Nope. Has to be something else.  

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ echo $GOPATH
/usr/local/gopkg

user@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/usr/local/gopkg/bin

**Comment by compleatang** [comment]
does `user` have write access to `/usr/local/gopkg/bin`?  

also `ls /usr/local/gopkg/bin` to see if it made `epm-binary-generator` ...

**Comment by pralhdes** [comment]
epm-binary-generator is being made. 

root@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go# ls /usr/local/gopkg/bin/
decerver  epm-binary-generator

Even root cannot make. 

root@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go# make
go install ./cmd/epm-binary-generator
make: go: Command not found
make: *** [all] Error 127

**Comment by compleatang** [comment]
weird. am assuming that $GOPATH/bin is in root's path there is no logical reason for this to happen.

**Comment by pralhdes** [comment]
Thanks for helping out guys. Root's $PATH was indeed the issue. I thought I set this and for good measure I was doing sudo -E so the environment variables are retained with sudo... yet... 

root@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

root@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go# export PATH=$PATH:/usr/local/go/bin:/usr/local/gopkg/bin

root@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/usr/local/gopkg/bin

root@host:/usr/local/gopkg/src/github.com/eris-ltd/epm-go# make
go install ./cmd/epm-binary-generator
epm-binary-generator ./cmd/epm ./commands thelonious tendermint ethereum

**Comment by compleatang** [comment]
great! good to hear it was solved!
