### ISSUE TITLE
EPM usage improvements

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#33]
Config stuff
- [x] There should be a global config that you can edit 
- [x] allow edit chain configs from command line
- [x] allow edit global configs from command line
- [x] Global config default log level should be 2 not 5
- [x] epm -init should not drop a local config unless an extra flag is used. The global one should be fine for most people most of the time

Cli stuff
- [x] epm -refs should highlight the chain you are currently on in another colour. I know you can get it from head but its just the little things
- [x] Clear out epm scratch before running
- [x] When a specified .pdx can not be found say that (log level 2)
- [x] Tab Completion of commands and chainid and chain names?
- [x] namereg per chain for easy finding contracts
- [x] *Big* If an argument is not recognized it should NOT run at all. currently it defaults to running as just epm which is annoying. If a help message popped up that would be great. or one that points you to epm -help
- [x] epm delete <chainid> or epm delete to delete checkouted chain. SHOULD GIVE WARNING and ask for confirmation
- [ ] epm fetch (see other issue for details)
- [x] remove install. From now we just should work from a global workspace.

PDX stuff
- [x] When a contract is deployed and named the result eg {{DOUG}}dougaddress should be available on all but log level 0
- [ ] diff should have better display when values are removed (set to 0) and contracts are suicided.
- [ ]  diff should have options for ESL pretty print 

EPM stuff
- [x] save epm vars to disk in blockchain dir
- [ ] check n args per command
- [ ] allow overwriting variables

iepm
- [ ] Ability to press up to use previously typed commands
- [ ] Ability to store typed commands into a .pdx file for which we supply the name
- [ ] single line deploy
- [ ] pipe flags to `epm -i`

Other chains
- [ ] standardize minimum blockchain config
- [ ] improve default configs for all modules
- [x] drop default config into `~/.decerver/blockchains/<chainType>` on deploy

**Comment by ebuchman** [comment]
This ought to be closed in favour of more specific issues.

@dennismckinnon if you have anything important here please group into new issues as you deem fit.
