### ISSUE TITLE
epm fetch functionality

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#40]
Epm fetch is currently tied to dapps but we should enable epm to fetch just by providing a chainid and an ipaddress (port if non-standard?).

format should be 

epm fetch <ipaddress:chainid> 

similar to the git clone this auto sets the "upstream" peer server in the config for the chain.

When you epm fetch it should get the genesis block from the peer the first time. It should then ask you if you would like to sync with the network. If you say "no" it should inform you something like:

"You can sync the chain later by running epm fetch again or epm run"

This step is just so that people are not forced to download really large chains right away.

*For Consideration* Should epm fetch allow for checkpointing inclusion? so you can fetch from the checkpoint on and not from the genesis block?

*For Consideration* much like git's set-upstream option should we have epm set-peer chainid to modify the peer server address in the config. Most of the config options we are specifically ignoring because it complexifies other module interaction. But maybe we should include this one since what chain won't need a peer address for bootstrapping?

**Comment by ebuchman** [comment]
https://github.com/eris-ltd/epm-go/commit/6c28c553de134f405d201e2388e099350fecbe11
