### ISSUE TITLE
Data Migration Ability

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#41]
To have EPM really shine, we need a way to migrate data out of existing databases and into blockchains. 

Customer bases, and other large data sets are currently held in centralized data stores. For those who want to decentralize their data stores we need them to be able to move data programmatically onto a predefined data pattern. 

DTT gets us a good bit of the way there on the smart contract side, but we still have to suck the data out of the sql and nosql databases in order to fire hose it onto the blockchain EPM had loaded. 

Trade offs are that this will add heft to EPM, but if we do it right (like a pdm file which maps data and contains the database connection info), this would be amazingly helpful.

**Comment by ebuchman** [comment]
this is a big issue and will probably get its own repo. we need a "blockchain" <-> "classic db" converter tool. I'm going to close this and we can start a repo for it if we want to seriously go after it

**Comment by compleatang** [comment]
agree.
