### ISSUE TITLE
Compilation moduling

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#44]
We should start using prefix driven typing of scripts/smart contracts.
I'm thinking things like: `.lll`, `.se`, `.sol`, `.btcop`, `evm`, `.bytes`, and `.hex`
Epm will keep a config of supported languages. For each, it will specify an extension,  remote server compiler, a local path compiler, and whether to use remote or local. 

The lllc-server can be generalized to provide compilation for all languages, the compilers for which we will take responsibility for installing and updating on an as needed basis on the compile server (note we should get a dedicated compile server). 

Technically this is something the decerver will find very useful as well, and something which we may which to provide js bindings for too

**Comment by ebuchman** [comment]
So a key here is that the `Script()` function in module wrappers will take byte code, rather than a file name. So blockchain modules should be written to rely on outside modules for compilation.

**Comment by dennismckinnon** [comment]
bitcoin opcodes.

If you don't know you can actually do scripting in bitcoin too. You place the script in opcode format in the transaction. though it doesn't have a compiled language its possible you would want to use EPM to construct and deploy scripted transactions. which honestly would be pretty flippin cool. I don't know of any tool that currently easily lets you do that.

**Comment by ebuchman** [comment]
thats what I meant by `btcop`! just the bitcin opcodes...
