### ISSUE TITLE
Genesis Config should be able to include a separate accounts.json

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#48]
This will be helpful for researchers (and probably for industry as well) as they can use separate tools to build the `accounts` array into its own json file rather than having to build that into the main config file.

By default I don't see any problem building it into the main json file, but it *could* be helpful in certain contexts to have the flexibility to do it separately. Obviously, though, this would require distribution of another file, so I'm wondering if epm should be able to read a separate accounts json file and pull that into the main genesisconfig.json so then that cohesive json could be distributed.

**Comment by ebuchman** [comment]
agreed. id let thelonious handle it tho rather than epm per i think. at least for now.

**Comment by compleatang** [comment]
my idea as to why putting that here in `epm` was because epm could just read accounts from a json array file and build the genesis.json before deploying the chain. then thel could take over using the newly build genesis.json. so it is just an ordering thing.

**Comment by ebuchman** [comment]
right but thats a chain specific thing to only thel. im trying to keep epm as chain agnostic as possible by putting that kind of thing in with the respectice chain.

maybe its a good idea to give epm more freedom with thel tho, as its kind of his mainstay?

**Comment by ebuchman** [comment]
right but thats a chain specific thing to only thel. im trying to keep epm as chain agnostic as possible by putting that kind of thing in with the respectice chain.

maybe its a good idea to give epm more freedom with thel tho, as its kind of his mainstay?

**Comment by compleatang** [comment]
I'm with you on chain agnosticism. Nothing wrong with adding some extras for thel chains tho. I mean you can't preset such things -- account balances and whatnot -- for Eth testnet or anything.

**Comment by dennismckinnon** [comment]
sort seems like we are getting to features of epm which should really installable scripts rather then built in features almost. All of these things we do are basically combinations of the core capabilities of EPM that could be coded in a .pdx So maybe we should extend the capabilities of .pdx's? i'm fine with short term solutions of course. But maybe we need to have a discussion about what direction we want epm to be taking long term? Will it be command line decerver? or do we keep it as git for blockchains? what are people going to need? What are we going to need?

**Comment by ebuchman** [comment]
new thel will start up with like 6 different json files to configure everything. accounts.json will be in there for sure (will add appropriate flags to `epm new` then)
