### ISSUE TITLE
Short tag for --name

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#49]
-n ???

Also, consider whether the name could default as the current directory? Just thinking about making `epm new` be as quick and short as possible...

**Comment by dennismckinnon** [comment]
-n ++
default naming --

In general we have been trying to move away from automated behaviours so you are always aware of what you are doing.

**Comment by compleatang** [comment]
:+1:

**Comment by dennismckinnon** [comment]
something we might consider is removing the optional name component and just force you to name a chain when you create one.

that wouldn't be the worst thing? thoughts @ebuchman that would remove the need for the addref command too

**Comment by ebuchman** [comment]
was jjust thinking about this. is there any case where you'll have or want to have a chain but no clean reference to it? sometimes i think working with the hashes might just be fine for ppl...

**Comment by compleatang** [comment]
Right. Also names could clog up if you were working on different things programmatically, so in that case you'd just be using the hash anyway...

**Comment by dennismckinnon** [comment]
fair enough. lets keep it. I was thinking what if we kept add-ref but removed the -n flag. and if you wanted to name it you type the name immediately after the `new` command that might be more complex though so whatever `-n` is my vote for the short form

also while we are at it i would rather -c to be checkout rather then config directory -o is not intuitive and   i rarely change the config from default anyways. if you make edits to the config.json in blockchains that would set your default settings correct?

**Comment by ebuchman** [comment]
yep. you can do that with `epm config -global` I believe

**Comment by ebuchman** [comment]
ok so. `epm new -n mychain` or `epm new mychain`

**Comment by ebuchman** [comment]
personally I'm for the former

**Comment by compleatang** [comment]
former.

**Comment by dennismckinnon** [comment]
both

... but i'll live with -n ... dowit

**Comment by androlo** [comment]
not sure if it matters, but most stuff i know use capital letters to abbreviate, like -N or --name would be the same.

**Comment by dennismckinnon** [comment]
most things i know use the capital form for a more powerful form like forced operations

-d delete if safe
-D force delete  for example

otherwise git uses primarily lowercase letters.

Also I do not want to hit two buttons simultaneously. :P

**Comment by androlo** [comment]
-N  - force name.

**Comment by dennismckinnon** [comment]
I think you intended this as a joke but there could be utility here. Names need to be unique so if you roll a chain and try to name it the same as an existing chain then it should throw and error (take note @ebuchman)

So once we get the ability to delete chains or whatever -N could remove the name from the old chain and give it to the new one. Seem reasonable?

**Comment by ebuchman** [comment]
ya great. also need to add delete ref. `epm refs rm <refname>` ? maybe then `add-ref` should be `epm refs add <chainId> <ref>` ?

**Comment by compleatang** [comment]
:+1:
