### ISSUE TITLE
testing conditions

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#5]
test: linkedlist
	Typical assertions with pass fail
	...
	(ability to assign values to variable)
onpass:
	Stuff to do on all of above passing
	... (probably empy most of the time)
onfail:
	Stuff to do on fail. notably
	dump {{contractaddress}} "tag" - dumps contract storage into testname.dump
							  pretty print the non-zero values?

**Comment by ebuchman** [comment]
@dennismckinnon do we still want this? what are your thoughts on this kind of thing

**Comment by dennismckinnon** [comment]
No

**Comment by dennismckinnon** [comment]
No. We dont need this. I suspect there will be better methods for working with this stuff soon.

**Comment by compleatang** [comment]
K. Closing for now. Let's reopen or add a new issue later if we need.
