### ISSUE TITLE
Integrations Test Suite

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#51]
I think we should start a repo to manage running tests, so we can get a clear set of integrations tests going. Then Cledus can import that repo and be test agnostic.

I will have to update him to deal with our branching workflow, but in the meantime will be easy to make a simple go program that will just charge through a bunch of pdxs.

@dennismckinnon, care to make a mini list here of pdx to include for optimal integrations testing?

**Comment by dennismckinnon** [comment]
everything in eris-std-lib/DTT/tests

By this weekend I plan on updating some things with it. I'll try to make the tests more comprehensive.

**Comment by ebuchman** [comment]
great. would love to see gendoug tests too when you ghet a chance

**Comment by dennismckinnon** [comment]
gendoug tests are harder because its all DTT which EPM doesn't know how to do...

**Comment by dennismckinnon** [comment]
not that this should stop us from implementing that feature because SUPER USEFUL

**Comment by compleatang** [comment]
integration_tests++

**Comment by ebuchman** [comment]
this will be up to the containers. give david a list of pdx/pdt files to use for integration tests
