### ISSUE TITLE
`epm kill` -> opposite of `epm run` 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#61]
could also be `epm stop`

**Comment by ebuchman** [comment]
why not `ctrl-c`? you want an extra server listening so we can `epm kill` a running node from another terminal?

**Comment by ebuchman** [comment]
`epm plop pid | xargs kill -2`

or `epm plop --chain <chain ref> pid | xargs kill -2` if its not checked out

**Comment by compleatang** [comment]
:shipit:
