### ISSUE TITLE
Make `config.json` optional for `epm new`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#63]
Here's the general pattern we will probably be using going forward for containers (in the container build process it will copy in the genesis.json). This is the shell program which will run the node.

```bash
epm new --name helloworld --checkout --genesis /home/$user/genesis.json
epm config serve_rpc:true rpc_port:30304 key_session:$key_name remote_host:104.236.146.58 use_seed:true
epm --log 5 run
```

I think it makes a lot more sense to operate in this fashion because the config vars sent to the `epm config` command can be used to read ENV Vars (as seen in the `key_session` set above). Dumping into the genesis.json screen on `epm new` makes sense to me because that is the configuration of that chain and we're establishing a new chain.

However, it makes less sense to me to dump into an editor and worry about `config.json` by default. Although you just shipped the `novi` option which could be used here, I'm not sure that we want to default edit the config at all. I think the defaults are sensible and likely folks will want to set defaults either explicitly or via an `epm config edit` command. Also, not one but two big walls of json when just learning `epm` may be somewhat of an impediment to folks trying out `epm` and not understanding the difference between what the two configs are used for.

Personally, I think it makes more sense to pass an `edit-config` flag if I want to edit it during the `new` process rather than having to go into it.

**Comment by ebuchman** [comment]
- [ ] open genesis.json only if no `--genesis`
- [ ] don't open config.json unless `edit-config`

https://github.com/eris-ltd/epm-go/commit/768add41371aa42b81e35ca7f24f904b6e4b03f8
