### ISSUE TITLE
#"ideas for review" Proper referencing of keys

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#71]
From my inspection it seems like key naming involves prefacing the key file name with the name of your choice. I assume that this is in order to do auto complete on just the name portion of the key. It seems like a proper refs system like that used on chains might be benefitial.  I tried adding the ideas for review tag to this but not sure billings is going to figure that out.

**Comment by compleatang** [comment]
its to provide a concise addr and key functionality. let's leave it as is.... `epm keys` is much more functional now and will handle this betterly.
