### ISSUE TITLE
bug with Recursive includes edits.

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#82]
It seems when you have an include structure that looks like:

A includes B,
B includes C

If you have already compiled A once and then edit C, (But not B!) the changes do not appear to be recognized. The changes will not be reflected in the compiled contract.

**Comment by ebuchman** [comment]
This has been fixed on lllc but of course stepping on an ant causes  circleCI to spontaneously combust, so bare with me
