### ISSUE TITLE
allow install of dapp on more than one chain

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/epm-go#95]
currently hindered by failing to copy the dapp into ~/.decerver/dapps if it already exists. but should allow to deploy on another chain...

**Comment by compleatang** [comment]
docker start scripts and env vars solve most of this. will backlog and you can close if you think we should handle at the docker level (which is my preference)

**Comment by ebuchman** [comment]
by concern was that running `epm installl hello-world-dapp helloworld` will fail if `helloworld` already exists in ~/.decerver/dapps. so if we want the same dapp installed on multiple chains, do we reuse the same dapp folder, or maybe tag them somehow so the js/scripts can vary between them if need be? thoughts?

**Comment by NodeGuy** [comment]
We should have only one dapp per decerver, which implies that `helloworld` will never already exist in `~/.decerver/dapps`.

**Comment by ebuchman** [comment]
but I may want to have helloworld on two different chains

**Comment by NodeGuy** [comment]
Unless you have a compelling need for this now, we should begin with "one blockchain, one dapp", and then refactor in the future.

**Comment by ebuchman** [comment]
I don't have a compelling need per se, but I can imagine an obvious intended use case of wanting the same dapp on different chains with different permissions structures. I will leave this aside until someone from the community or yourself decides they really want it :)

**Comment by dennismckinnon** [comment]
The flawed one dapp per decerver arguement doesnt capture the real reason this should not be supported. 

If you want the same code for a dapp but on a different chain you should put it in a new folder. The reason is that the decerver can not specify which to put in focus when you ask for the dapp. In short if it has a different package.json it should have its own folder. 

Unless you want to rewrite the decerver...

**Comment by compleatang** [comment]
I think most of the challenge here is that the current decerver conflates a few things and is doing too much. 

The switch to using a slimmed down decerver-go as the cap for epm running a particular chain `+` docker to manage container start up and configuration `+` decerver-node as middlewear will largely solve this issue I think. :dancers: 

That will (potentially) allow us to move away from using the (probably overly rigid) `package.json` to define how low level modules should be configured and instead use simple `fig.yml` which can be shared in numerous ways (GH, ipfs, w/e).

**Comment by ebuchman** [comment]
@dennismckinnon I was thinking the dapp folders would be suffixed with a chain id or index so `~/.decerver/dapps/helloworld-f85...` kind of thing.

I will simply close for now until it might matter again. we can always also just use a different $DECERVER if/when this kind of thing is needed.

**Comment by compleatang** [comment]
good point. i like the $DECERVER idea...
