### ISSUE TITLE
more thoroughly test cli interactions

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#98]
should os.Exec("epm ....") and make sure it performs as expected for all `cli` based actions.

**Comment by ebuchman** [comment]
I suspect we might be better off doing this from docker/bash and basing it on some of the dapp deploys or whatever that we already have. thoughts?

**Comment by compleatang** [comment]
many ways to do it. basically we need to just run each of the cli commands to make sure they are operational during the testing phase. could do from a go_test file with os.Exec or from bash. Either one will work.

the idea is to have the tests keep us in line as to what the cli commands, subcommands, and flags do. 

i'll work on this in concert with epm serve as there is a bit of overlap (as `epm serve` will start as an http api accessible link to the epm cli)...

**Comment by compleatang** [comment]
https://github.com/docker/docker/tree/master/integration-cli

**Comment by compleatang** [comment]
moving to 0.10. this is fairly well tested but we should add some more resiliency here (also I want to connect the testing framework -- predominantly circle.yml -- up to the sites in a bit better way)

**Comment by compleatang** [comment]
this is working fine now.
