### ISSUE TITLE
epm serve

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#99]
TODOs:

- [x] `epm` commands
  - [x] checkout 
  - [x] rm (chain)
  - [x] keys (import only)
  - [x] new
  - [x] config
  - [x] cp
  - [x] fetch
  - [x] start (run)
  - [x] stop (kill)
  - [x] restart
  - [x] plop
  - [x] refs
- [x] normal `monk` API commands
  - [x] monk commands should "fall thru" to the RPC handler

**Comment by androlo** [comment]
the decerver http and websocket servers are made to pass pretty much everything to ate. I can create a new version, perhaps in decerver-modules or something for now. It would have none of the ate stuff left, but instead be ready to use normally. I already started working on that before i saw thelonious has rpc already (and even the calling code in modules, that epm uses).

even if you are going to design it Casey i think maybe an ate-free version would be a better starting point. it would still allow http and websocket connections, and multiple websocket connection at the same time.

**Comment by compleatang** [comment]
yes, that is exactly what i'll be working on. agree we won't be using ate

**Comment by androlo** [comment]
I'm on this btw.

**Comment by compleatang** [comment]
you are? as in you're doing it?

**Comment by androlo** [comment]
I'm making the basis, removing Ate and replacing some bad things. It'll be ready tonight probably. I can continue on adding endpoints later and make tests as well if you want, but we should discuss the endpoint names and such in that case.

**Comment by androlo** [comment]
Could make the webAPI document too I guess, unless you really want to do some of these things.

**Comment by compleatang** [comment]
OK. So the discussion for the endpoints needs to be in the API spec document. Please push your work to a branch in this repository so that I can work to add what I've been working on, add the tests, etc. After that I will take over maintaining it so that you can get back to your work on the education side.

**Comment by androlo** [comment]
Ok, I will not be able to implement any of the epm api methods, because a lot of that logic is in package protected methods under cmd/epm, but I will finish the server and make some basic server tests.

**Comment by ebuchman** [comment]
ya so the main reason it's like that is because those functions all take a pointer to the `cli.Context` struct. I'm not sure if you can build those ahead of time and pass them in as a way to carry the params. but casey and I were talking about adding an extra layer there so we could make the actual functions public and just pass in all possible params (which might lead to a messy api...)

**Comment by compleatang** [comment]
For now I think it best that Andreas just finish up your work and push and then Ethan and I will take a look and see what makes sense for the tool overall.

**Comment by androlo** [comment]
Ok so I'm thinking we can use [WAMP](https://github.com/tavendo/WAMP/blob/master/spec/basic.md) for the websocket stuff and set the server up as a dealer + callee. Gonna need some type of socket rpc protocol. Basic WAMP looks like a decent one, is an officially recognized sub-protocol etc.

**Comment by compleatang** [comment]
Potentially we could use [this](https://github.com/jcelliott/turnpike) as a base.

**Comment by androlo** [comment]
nice. ok ill look over it tomorrow and wrap up the websocket stuff then. guess also json rpc can be used  until something like this is added, or just leave it unimplemented for now. isn't much i can do with just the http until this epm api stuff has been sorted out.

**Comment by androlo** [comment]
it's in decerver on erisdb branch for now. changed my mind.

**Comment by compleatang** [comment]
OK. Well, let me know when you're finished with this first round so that I can add my stuff and move it over to this repo where it needs to be, add tests, and do the rest.

**Comment by androlo** [comment]
Done with first round.

**Comment by compleatang** [comment]
Awesome!

**Comment by androlo** [comment]
Created 1k websocket sessions asynchronously that ran the websocket echo test, all of them seem to have passed. Looks pretty solid.

**Comment by androlo** [comment]
(and was added and removed successfully)

**Comment by androlo** [comment]
Can't we just break the epm api out of the cli, it's like 10 methods, should not take long. would be really, really nice to get some other eris stuff into decerver-node.

**Comment by androlo** [comment]
server already done, just waiting for something to actually do.

**Comment by ebuchman** [comment]
status on this? you guys need more from me?

**Comment by compleatang** [comment]
its gonna be a bit more time, but we shouldn't need anything from you as of now.

**Comment by compleatang** [comment]
This basically done. The only thing we are currently lacking is RPC tests for Thelonious.

**Comment by compleatang** [comment]
Done. Deprecating issue in favor of #168
